config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/:username', to: 'github_profile#show'

  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/git_hub_gist.rb
class GitHubGist

  def initialize(raw_gists)
    @raw_gists = raw_gists
  end

  def gists
    @raw_gists.map do |gist|
      { url: gist[:html_url], description: gist[:description], comments: gist[:comments], created_at: gist[:created_at]}
    end[-6..-1]
  end

end

app/models/git_hub_profile.rb
class GitHubProfile
  attr_reader :name,
              :screen_name,
              :bio,
              :location,
              :url,
              :image,
              :number_repos,
              :followers,
              :following

  def initialize(raw_profile)
    @image        = raw_profile[:avatar_url]
    @name         = raw_profile[:name]
    @screen_name  = raw_profile[:login]
    @bio          = raw_profile[:bio]
    @location     = raw_profile[:location]
    @url          = raw_profile[:blog]
    @number_repos = raw_profile[:public_repos]
    @followers    = raw_profile[:followers]
    @following    = raw_profile[:following]
  end
end

app/models/git_hub_repo.rb
class GitHubRepo

  def initialize(raw_repos)
    @raw_repos = raw_repos
  end

  def repos
    @raw_repos.map do |repo|
      { name: repo[:name], url: repo[:html_url], language: repo[:language]}
    end[0..5]
  end

end

app/models/git_hub_user.rb
class GitHubUser
  attr_reader :name, :screen_name, :bio, :location, :url, :image

  def initialize(raw_profile)
    @image        = raw_profile[:avatar_url]
    @name         = raw_profile[:name]
    @screen_name  = raw_profile[:login]
    @bio          = raw_profile[:bio]
    @location     = raw_profile[:location]
    @url          = raw_profile[:blog]
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name, :uid, :screen_name, :oauth_token

  def self.from_omniauth(auth_info)
    if find_by(uid: auth_info[:uid])
      find_by(uid: auth_info[:uid]).update(oauth_token: auth_info[:credentials][:token])
    else
      create do |new_user|
        new_user.uid                = auth_info.uid
        new_user.name               = auth_info.extra.raw_info.name
        new_user.screen_name        = auth_info.extra.raw_info.login
        new_user.oauth_token        = auth_info.credentials.token
      end
    end
    find_by(uid: auth_info[:uid])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/github_profile_controller.rb
class GithubProfileController < ApplicationController
  def show
    @github_profile ||= GitHubProfileService.new(current_user.oauth_token).profile
    @github_repos ||= GitHubRepoService.new(current_user.oauth_token).repos
    @github_gists ||= GitHubGistService.new(current_user.oauth_token).gists
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/github_profile/show.html.erb
<%= stylesheet_link_tag "show" %>
<section class = 'main'>
  <section class = 'main-left'>
    <%= image_tag @github_profile.image, :class => "profile-image" %>
    <p class = 'name'><%= @github_profile.name %></p>
    <p class = 'screen_name'><%= @github_profile.screen_name %></p>
    <p class = 'bio'><%= @github_profile.bio %></p>
    <div class="hr-line"></div>
    <p class = 'location'><%= @github_profile.location %></p>
    <p><%= link_to 'LinkedIn Profile', @github_profile.url %></p>
  </section>
  <section class = 'main-right'>
    <section class = 'top'>
      <p class = 'repos'>Repositories: <%= @github_profile.number_repos %></p>
      <p class = 'followers'>Followers: <%= @github_profile.followers %></p>
      <p class = 'following'>Following: <%= @github_profile.following %></p>
    </section>
    <h2 class = 'repos-gists-title'>Latest 6 Repositories</h2>
    <section class = 'middle'>
          <p><% @github_repos.each do |repo| %></p>
          <section class = 'card'>
            <p><%= link_to repo[:name], repo[:url], :class => "card-link" %></p>
            <p class = 'card-description'><%= repo[:language] %></p>
          </section>
          <% end %>
    </section>
    <h2 class = 'repos-gists-title'>6 Private Gists</h2>
    <section class = 'bottom'>
      <p><% @github_gists.each do |gist| %></p>
      <section class = 'card'>
        <p><%= link_to gist[:description], gist[:url], :class => "card-link" %></p>
        <p class = 'card-description'><%= gist[:created_at] %></p>
      </section>
      <% end %>
    </section>
  </section>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apicurious</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'reset', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="navbar">
      <a><%= image_tag 'github.png', :class => "main-logo"%></a>
      <% if current_user  %>
        <section class="admin">
          <%= image_tag 'mini_pic.jpeg', :class => "admin-logo" %>
          <%= link_to 'Logout', logout_path, method: :delete, :class => "admin-logo-text" %>
        </section>
      <% else %>
        <section class="admin">
          <%= image_tag 'person-1.png', :class => "admin-logo" %>
          <%= link_to 'Sign in with GitHub', github_login_path, :class => "admin-logo-text" %>
        </section>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag "show" %>
<% if current_user  %>
  <h3 class="login-main-title">Welcome, <%= current_user.name %><br></h3>
  <%= link_to image_tag("profile.jpeg", height: 100, width: 300), "/#{current_user.screen_name}", :class => 'welcome_profile' %>
<% else %>
  <div class="welcome-page">
    <p>Welcome to Apicurious</p>
  </div>
<% end %>